### ISSUE TITLE
辞書順のbox listがほしい

### ISSUE THREAD

**Issue by Szkieletor37** [hakatashi/esolang-box#57]
どの言語のboxがあるか探しにくいので、
・アルファベット順の言語リスト
・汎用や関数型など、カテゴリ別
のリストを作りたいのですが、この場合はreadme.mdにPRを出すか、Wikiを使うかどちらがいいと思いますか。

**Comment by hakatashi** [comment]
誰でもすぐ編集できるべきだと思うので、Wikiがいいと思う

**Comment by Szkieletor37** [comment]
GitHub Wikiを編集する権限がなさそう（付いてますか）

**Comment by Szkieletor37** [comment]
@hakatashi 編集って誰でもできるようになってますか？ collabolatorだけですか？
https://docs.github.com/ja/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

**Comment by hakatashi** [comment]
@Szkieletor37 開放した
