### ISSUE TITLE
Whitespace disassembly bug

### ISSUE THREAD

**Issue by platypus999** [hakatashi/esolang-box#69]
## Summary ##
Whitespace は `<Space>` と `<Tab>` の 0 文字以上の組み合わせをタグとして用いることができる（つまり、空文字列もタグになりうる）
だが、box の disasm で用いられているプログラムでは整数リテラルと同じく`<Space>` と `<Tab>` の **1 文字以上**の組み合わせを期待しているため、空文字列をタグとして用いるプログラムの disasm に失敗する。

### Possible solutions ###
現在使っている disasm にパッチを入れることは手間がかかりすぎると思うので、別の disassembler (例えば[これ](https://github.com/zorchenhimer/whitespace)は空文字列タグをきちんと認識する) を導入するといいと思う

**Comment by hakatashi** [comment]
Resolved by #70.
